### PR TITLE
#8 Added project to create a nuget package

### PR DESCRIPTION
**Pull request by drmason789**
Unfortunately with .NET Framework projects unlike newer project types, you can't just fill in some project details and run dotnet pack.

Here I've made a project which uses scripts to call nuget.exe on a nuspec file to package oledump.exe and its dependencies for distibution from nuget.org.

Here's what it looks like when managing a solution's packages.

image

### CODE REVIEW

**Comment by bclothier** [comment]
Perhaps I've missed it but how will we handle 32-bit/64-bit? The `olewoo_interop` project for which the C# portion, including the `oledump.exe` depends on must be cross-compiled in order to work for either 32-bit or 64-bit.

**Comment by drmason789** [comment]
See issue #10.

**Comment by drmason789** [comment]
I think the nuspec needs some tags to assist with searches.
I'm thinking oleview, olewoo, typelib, "type library", tlb, midl, com.

Any other suggestions?

**Comment by drmason789** [comment]
@leibnitz27 It would be simpler to simply use the plain MIT license rather than the full content of the licence.txt file. With your agreement I will make this change.

**Comment by drmason789** [comment]
Here's what it looks like currently:

image

**Comment by drmason789** [comment]
I've actually got this working now using "dotnet pack" or msbuild in another project, i.e. without having the nuget project and cmd script.

I recommend holding off on this PR while I explore the simpler option. I'm still looking for preferences on the field content (description, license etc).

**Comment by leibnitz27** [comment]
Ack.  I'm fine with replacing the snarky comments with the standard MIT license ;)

**Comment by bclothier** [comment]
> See issue #10.

IINM, that means the oledump cannot read 64-bit type libraries. The assumption is that there'll be a 32-bit counterpart but that need not be the case, and even if there was, there's no guarantee that the 32-bit version is 100% identical to the 64-bit version.

**Comment by drmason789** [comment]
> I've actually got this working now using "dotnet pack" or msbuild in another project, i.e. without having the nuget project and cmd script.
> 
> I recommend holding off on this PR while I explore the simpler option. I'm still looking for preferences on the field content (description, license etc).

It's not looking simpler, actually. Despite being given the --no-build arg, dotnet.exe still doesn't just copy the pre-existing outputs into the package, and gets caught up on a props file it can't find. But even with the script below, it doesn't find the project outputs.

I've had a success using msbuild -t:pack with this instead, but it didn't work out oledump's dependencies and include them automatically.

I am now in favor of sticking with the nuget project. 

```
@echo off
setlocal

set config=%~1


if "%config%"=="" (
	echo Build configuration DEBUG^|RELEASE should be specified as the first command line argument.
	goto :error
)

where dotnet.exe > nul
if errorlevel 1 (
	echo dotnet.exe not found. Please install .NET Core.
	goto :error
)


set outputFolder="%~dp0..\%config%"
call :ensureOutputFolder %outputFolder%
if errorlevel 1 goto :error


cd /d "%~dp0\..\oledump"
if errorlevel 1 (
	echo Failed to change to oledump project folder
	goto :error
)

if "%VCTargetsPath%"=="" (
	call :SetUpVCTargetsPath
	if errorlevel 1 goto :error
)

dotnet pack oledump.csproj --no-build -c "%config%"  --output %outputFolder%
if errorlevel 1 goto :error

goto :eof

:SetUpVCTargetsPath

set tempFile="%temp%\props.txt"
where /R "%ProgramFiles(x86)%" microsoft.cpp.default.props > %tempFile%
if errorlevel 1 (
	echo Could not find microsoft.cpp.default.props
	exit /b 1
)
for /f "tokens=*" %%f in ('type %tempFile%') do set VCTargetsPath=%%~dpf

goto :eof

:ensureOutputFolder 
rem expects the output folder as %1
if exist "%~1\" goto :eof

md "%~1"
if errorlevel 1 (
	echo Failed to create output folder %~1
	exit /b 1
)

goto :eof

:error
echo ERROR
exit /b 1
```

**Comment by drmason789** [comment]
> > See issue #10.
> 
> IINM, that means the oledump cannot read 64-bit type libraries. The assumption is that there'll be a 32-bit counterpart but that need not be the case, and even if there was, there's no guarantee that the 32-bit version is 100% identical to the 64-bit version.

I just exported a .NET assembly to a tlb using "tlbexp assembly.dll /win64 /out:x.tlb" and both oledump.exe and olewoo_ui.exe built for x86 opened it without error.

**Comment by drmason789** [comment]
Here's where I'm at:

1. I have explored putting the nuget properties in the oledump.csproj file and using msbuild or dotnet to pack the nupkg, but have found this complicated. I want to stay with the csproj dedicated to calling nuget on a nuspec file.
2. I would like the owners to confirm the field values:
- id: OleWoo.OleDump
- description: Command line tool that dumps type library files to IDL (Interface Definition Language).
- authors: OleWoo
- projectUrl: https://github.com/leibnitz27/olewoo
- copyright: Lee Benfield &#169; 2010-2020
- tags: oleview olewoo typelibrary "type library" typelib tlb idl midl "interface definition language" tlbexp com
3. I believe there is no problem with oledump/olewoo_ui built for x86 loading 64-bit type libraries. Unless my test is invalid because I exported from an AnyCPU assembly.

**Comment by bclothier** [comment]
Regarding cross compiled TLB & reading, I guess I'm confused because my findings coincides with your finding; I made a dummy IDL file, compiled it using `midl.exe` with `/win64` flag and the `oledump.exe` had no problem reading it. I also confirmed that I could load using `oleview` and `oledump` both `C:\Windows\SysWOW64\scrrun.dll` and `C:\Windows\System32\scrrun.dll`.

[This implies that on 64-bit system, type libraries are registered for both bitness](https://www.howtobuildsoftware.com/index.php/how-do/hwC/windows-winapi-com-registry-typelib-icallfactory-with-32-bit-and-64-bit-type-libraries-side-by-side), but that seems to deal more with the registration things rather than the type library itself. Unless the native `LoadTypeLib` is doing something magical*, it's not clear to me why this isn't an issue, and it feels weird that it apparently works despite having the `/win32` and `/win64` flags for cross-compiling type libraries. 

Either way, that does makes my original concern apparently moot... 


* The official docs does mention registering the type library under certain conditions automatically but I don't see any registration happening in my tests.

**Comment by drmason789** [comment]
I believe the registration is just for telling Windows where to find things. As far as olewoo_interop and the API it uses are concerned, the type libraries are just files to be read and interpreted.

**Comment by drmason789** [comment]
It currently looks like this:

image

**Comment by drmason789** [comment]
In my last commit, I got rid of the cmd file and the direct need for nuget.exe. I've kept the separate project so that the nuget package can be compiled separately from oledump.exe, and not built every time oledump.exe is built. Instead of the cmd script that finds nuget.exe and uses it to build the package, I'm using a task from the nuget.build.tasks.pack package in the project file to do basically the same thing.

**Comment by leibnitz27** [comment]
Hey - sorry, I'm not ignoring this commit, but have a lot of stuff atm - will look soon!

**Comment by drmason789** [comment]
Ping.

**Pull request merged**
